config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"

   root "home#index"
   get "dashboard", to: "home#dashboard"

   resources :organizations, only: [:index] do 
    resources :memberships do
      collection do
        post :invite
      end
    end
  end
  resources :blogs do
    resources :comments
      collection do
        get :my_blogs  
      end
  end
  
  devise_for :users, controllers: {
  registrations: 'users/registrations'
}

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  
   
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :organization
  belongs_to :user

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]
  # before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.where(organization_id: current_user.organizations.pluck(:id))
  end
  
  def my_blogs
    @blogs = Blog.where(user_id: current_user.id, organization_id: current_user.organizations.pluck(:id))
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)
    # @blog.organization_id = current_user.organization_id 
    @blog.organization_id = current_user.organizations.first.id
    @blog.user_id = current_user.id 

    respond_to do |format|
    if @blog.save
      format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
      format.json { render :show, status: :created, location: @blog }
    else
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @blog.errors, status: :unprocessable_entity }
    end
  end
end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy!

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_blog
      @blog = Blog.find(params[:id])
    end
  
    def authorize_user!
      unless @blog.user == current_user
        redirect_to blogs_path, alert: "You are not authorized to perform this action."
      end
    end
  
    def blog_params
      params.require(:blog).permit(:title, :body, :organization_id, :user_id)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <p>
    <strong>Title:</strong>
    <%= blog.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= blog.body %>
  </p>

  <p>
    <strong>Organization:</strong>
    <%= blog.organization_id %>
  </p>

</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>



  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<% content_for :title, "Editing blog" %>

<h1>Editing blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", @blog %> |
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Blogs" %>

<h1>Blogs</h1>

<div id="blogs">
  <% @blogs.each do |blog| %>
    <%= render blog %>
    <p>
      <%= link_to "Show this blog", blog %>
    </p>
  <% end %>
</div>

<%= link_to "New blog", new_blog_path %>

app/views/blogs/my_blogs.html.erb
<h1>My Blogs</h1>

<% if @blogs.any? %>
  <% @blogs.each do |blog| %>
    <div class="blog">
      <h2><%= link_to blog.title, blog_path(blog) %></h2>
      <p><%= truncate(blog.body, length: 100) %></p>
      <small>Posted on <%= blog.created_at.strftime("%B %d, %Y") %></small>
    </div>
  <br/>
  <% end %>
<% else %>
  <p>You haven't posted any blogs yet.</p>
<% end %>

app/views/blogs/new.html.erb
<% content_for :title, "New blog" %>

<h1>New blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/show.html.erb
<p style="color: green"><%= notice %></p>
  <%= render @blog %>
  <div>
    <% if @blog.user == current_user %>
      <%= link_to "Edit this blog", edit_blog_path(@blog) %> |
        <%= link_to 'Delete', @blog,
            data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
      <% end %>
  </div>

  <hr>

  <h2>Comments</h2>
    <%= render @blog.comments %>
  <hr>
  
<h2>Add a comment </h2>
<%= render "comments/form" %>
<%= link_to "Back to blogs", blogs_path %>