config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"

   root "home#index"
   get "dashboard", to: "home#dashboard"

   resources :organizations, only: [:index] do 
    resources :memberships do
      collection do
        post :invite
      end
    end
  end
  resources :blogs do
    resources :comments
      collection do
        get :my_blogs  
      end
  end
  
  devise_for :users, controllers: {
  registrations: 'users/registrations'
}

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  
   
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Multi Tenant App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-dark">
 
  <% if signed_in? %>
  <ul class="navbar-nav mr-10px">
  <li class="nav-item active">

    <%= link_to "Home", root_path %>
    </li>
  <li class="nav-item active">

    </li>
    <%= link_to "Dashboard", dashboard_path %>
    <%= link_to "Organizations", organizations_path %>
    <%= link_to "Blogs", blogs_path %>
    <%= link_to "My Blogs", my_blogs_blogs_path%>
    <%= button_to 'Log out', destroy_user_session_path, method: :delete %>  <% else %>
    <%= link_to 'Sign in', new_user_session_path %>
    </ul>
  <% end %>
  </nav>
  
  <%= yield %>
  </body>
</html>